; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\naoya\Documents\Visual Studio 2010\npca.jp\3Dモニター制作\3DMonitor-Direct2D\3DMonitor\globals.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?win_engine@@3PAVWinEngine@@A			; win_engine
PUBLIC	?frame_counter@@3JA				; frame_counter
_BSS	SEGMENT
?win_engine@@3PAVWinEngine@@A DD 01H DUP (?)		; win_engine
?frame_counter@@3JA DD 01H DUP (?)			; frame_counter
_BSS	ENDS
END
